"""added explanation version

Revision ID: 07cb99d91120
Revises: 756a2a32805b
Create Date: 2024-02-26 14:09:16.396930

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '07cb99d91120'
down_revision = '756a2a32805b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('explanation_version', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.drop_column('explanation_version')

    # ### end Alembic commands ###
