"""added consent columns

Revision ID: 0c20435d96d9
Revises: 1b464ead80e8
Create Date: 2023-12-12 11:38:33.056760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0c20435d96d9'
down_revision = '1b464ead80e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.add_column(sa.Column('read_pis', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('understood_pis', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('participation_voluntary', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('information_consent', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('data_access', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('anonymised_excerpts', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('results_published', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('take_part', sa.String(length=16), nullable=False))
        batch_op.add_column(sa.Column('participant_name', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('date', sa.String(length=32), nullable=False))
        batch_op.add_column(sa.Column('email', sa.String(length=128), nullable=False))
        batch_op.add_column(sa.Column('keep_me_updated', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('consent', schema=None) as batch_op:
        batch_op.drop_column('keep_me_updated')
        batch_op.drop_column('email')
        batch_op.drop_column('date')
        batch_op.drop_column('participant_name')
        batch_op.drop_column('take_part')
        batch_op.drop_column('results_published')
        batch_op.drop_column('anonymised_excerpts')
        batch_op.drop_column('data_access')
        batch_op.drop_column('information_consent')
        batch_op.drop_column('participation_voluntary')
        batch_op.drop_column('understood_pis')
        batch_op.drop_column('read_pis')

    # ### end Alembic commands ###
