"""added more columns to post study survey

Revision ID: 26e43dc59522
Revises: 20bcb94dfbd6
Create Date: 2024-02-20 10:50:01.275557

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26e43dc59522'
down_revision = '20bcb94dfbd6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.VARCHAR(length=16),
               type_=sa.Integer(),
               existing_nullable=False)

    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.add_column(sa.Column('factors_in_data', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('understood', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('change_detail_level', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('need_support', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('understood_causality', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('use_with_knowledge', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('no_inconsistencies', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('learn_to_understand', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('need_references', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('efficient', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('survey', schema=None) as batch_op:
        batch_op.drop_column('efficient')
        batch_op.drop_column('need_references')
        batch_op.drop_column('learn_to_understand')
        batch_op.drop_column('no_inconsistencies')
        batch_op.drop_column('use_with_knowledge')
        batch_op.drop_column('understood_causality')
        batch_op.drop_column('need_support')
        batch_op.drop_column('change_detail_level')
        batch_op.drop_column('understood')
        batch_op.drop_column('factors_in_data')

    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.alter_column('age',
               existing_type=sa.Integer(),
               type_=sa.VARCHAR(length=16),
               existing_nullable=False)

    # ### end Alembic commands ###
