"""made column optional

Revision ID: 583864818fc9
Revises: e8a439347726
Create Date: 2024-01-30 10:29:17.741113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '583864818fc9'
down_revision = 'e8a439347726'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_time',
               existing_type=sa.INTEGER(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_time',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
