"""updated sample to create entery at start of sample display

Revision ID: 5bf5ece457dc
Revises: 5a3aef2aeab4
Create Date: 2024-02-27 15:32:03.660134

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5bf5ece457dc'
down_revision = '5a3aef2aeab4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('malignant',
               existing_type=sa.BOOLEAN(),
               nullable=True)
        batch_op.alter_column('complete_time',
               existing_type=sa.DATETIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('complete_time',
               existing_type=sa.DATETIME(),
               nullable=False)
        batch_op.alter_column('malignant',
               existing_type=sa.BOOLEAN(),
               nullable=False)

    # ### end Alembic commands ###
