"""added ai_use to sample table

Revision ID: 6465535e651d
Revises: c04d916d6122
Create Date: 2024-06-20 13:40:40.542749

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6465535e651d'
down_revision = 'c04d916d6122'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ai_use', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.drop_column('ai_use')

    # ### end Alembic commands ###
