"""added sort table

Revision ID: 756a2a32805b
Revises: 26e43dc59522
Create Date: 2024-02-20 11:56:36.621324

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '756a2a32805b'
down_revision = '26e43dc59522'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('concept_sort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('participant_id', sa.Integer(), nullable=False),
    sa.Column('action_time', sa.Integer(), nullable=False),
    sa.Column('update_value', sa.String(length=8), nullable=False),
    sa.Column('sample_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['participant_id'], ['participant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('concept_sort', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_concept_sort_participant_id'), ['participant_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('concept_sort', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_concept_sort_participant_id'))

    op.drop_table('concept_sort')
    # ### end Alembic commands ###
