"""changed ints to datetime

Revision ID: b24f0f09646e
Revises: c98615cfcdcb
Create Date: 2024-02-27 13:58:25.771806

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b24f0f09646e'
down_revision = 'c98615cfcdcb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('last_action_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)
        batch_op.alter_column('action_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=True)

    with op.batch_alter_table('concept_sort', schema=None) as batch_op:
        batch_op.alter_column('action_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)

    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('start_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)
        batch_op.alter_column('complete_time',
               existing_type=sa.INTEGER(),
               type_=sa.DateTime(),
               existing_nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('complete_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)
        batch_op.alter_column('start_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('concept_sort', schema=None) as batch_op:
        batch_op.alter_column('action_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=False)

    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('action_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)
        batch_op.alter_column('last_action_time',
               existing_type=sa.DateTime(),
               type_=sa.INTEGER(),
               existing_nullable=True)

    # ### end Alembic commands ###
