"""converted int column to string

Revision ID: eb14e1648a52
Revises: 6465535e651d
Create Date: 2024-06-25 11:51:02.364435

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb14e1648a52'
down_revision = '6465535e651d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('ai_use',
               existing_type=sa.INTEGER(),
               type_=sa.String(length=4),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sample', schema=None) as batch_op:
        batch_op.alter_column('ai_use',
               existing_type=sa.String(length=4),
               type_=sa.INTEGER(),
               existing_nullable=False,
               existing_server_default=sa.text("'0'"))

    # ### end Alembic commands ###
