"""made columns optional

Revision ID: edb67ca770f0
Revises: 583864818fc9
Create Date: 2024-01-30 11:02:47.799914

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edb67ca770f0'
down_revision = '583864818fc9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('last_action_time',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('update_value',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.alter_column('reset_pressed',
               existing_type=sa.BOOLEAN(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('action', schema=None) as batch_op:
        batch_op.alter_column('reset_pressed',
               existing_type=sa.BOOLEAN(),
               nullable=False)
        batch_op.alter_column('update_value',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('last_action_time',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###
