"""added participant id to demographic

Revision ID: edbce31f650c
Revises: eb14e1648a52
Create Date: 2024-08-13 10:22:05.121261

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'edbce31f650c'
down_revision = 'eb14e1648a52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.add_column(sa.Column('participant_id', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('demographic', schema=None) as batch_op:
        batch_op.drop_column('participant_id')

    # ### end Alembic commands ###
